blank_issues_enabled: false
contact_links:
  - name: 关于主题使用问题
    url: https://github.com/valor-x/hexo-theme-solitude/discussions
    about: 一些使用上碰到的问题 Discussion 询问。 Please ask questions in Discussion.

  - name: Solitude Q&A
    url: https://docs.efu.me/faq
    about: Solitude Q&A

  - name: QQ群
    url: https://qm.qq.com/q/mxfomMvJPG
    about: 新建立的QQ群

  - name: Discord
    url: https://discord.gg/Y8VEvVgW
    about: 'Official Discord Group'

  - name: Telegram
    url: https://t.me/solitudePro
    about: 'Official Telegram Group'
