name: Issue Question

on:
  issues:
    types: [labeled]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'question'
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v2.0.0
        with:
          actions: "create-comment"
          token: ${{ secrets.ISSUSE_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello! 👋
            
            Thank you for submitting your question. To ensure we can provide the best answer possible, could you please confirm you've provided the following details:
            - A clear and concise description of your question.
            - Any relevant code snippets or links to your project.
            - What you've tried so far in attempting to solve your issue.
            
            In the meantime, you might find the answer to your question in our [FAQs](https://solitude-docs.efu.me/faq) or [documentation](https://solitude-docs.efu.me/).
            
            We aim to respond to questions within 48 hours. If your question is urgent, please consider reaching out through our support channels.
            
            Thanks again for reaching out, and we look forward to assisting you!
